# Site settings

title: Mike Francis
email: mikeffrancis@gmail.com
description: 'Designer and developer.'
baseurl: ''
url: 'http://mikefrancis.me'


# Build settings

markdown: kramdown
permalink: /work/:title


# Sass

sass:
  style: :compressed